In [ ]:
import numpy as np
import random as rd
import math
import pandas as pd

In [ ]:
def create_week(week_len, num_slots):
  week_array = np.zeros((week_len, num_slots))
  return week_array

In [ ]:
empty_week = create_week(7, 24)

In [ ]:
def get_zeros(lst, min, max):
  return [i+min for i, e in enumerate(lst[min:max]) if e == 0]

In [ ]:
def num_pieces(num,lenght, max):
    number = num
    ot = list(range(1,lenght+1))[::-1]
    all_list = []
    for i in range(lenght-1):
      n = 1000
      while n > max:
        n = rd.randint(1, num-ot[i])
      all_list.append(n)
      num -= n
    all_list.append(num) 
    if all_list[-1] > max:
       num_pieces(number,lenght, max)

    return all_list

In [ ]:
def imb_week(num_days,  late):
  week = [0,0,0,0,0,0,0]
  lst = []
  for i in range(num_days):
    lst.append(rd.randint(i+1,i+2))
  if not late:
    lst = sorted(lst, reverse=True)
  week[len(week)-num_days-1:num_days+1] = lst
  
  return week
    

In [ ]:
def populate_calendar_2(max_per_day, week_type, day_type, b2b):

  empty_calendar = create_week(7, 24)
  
  day_start = 5
  day_end = 23
  week_len = 5
  #actual_per_day = rd.randint(max_per_week-2, max_per_day)
  
  early_week_idx = round(week_len//2)
  late_week_idx = round(week_len//2+1)
  max_per_week=week_len*max_per_day


  late_in_day = round(0.7*max_per_day)
  late_in_week = round(0.7*max_per_week)

  early_in_day = max_per_day - late_in_day
  early_in_week = max_per_week - late_in_week

  if week_type == None:

    week_lst =  [0,0,0,0,0,0,0]

    for i in range(len(week_lst)-week_len-1,week_len+1):
       week_lst[i] = rd.randint(max_per_day-2,max_per_day)
    #print('week_list:', week_lst)

    if day_type == None:

      for i in range(len(week_lst)):
        if b2b:
          r = rd.randint(1,2)
        else:
          r = rd.randint(2,3)
        idx_start = rd.randint(day_start, day_end - week_lst[i]*r)-r
        
        for j in range(week_lst[i]):
          idx_start +=r
          empty_calendar[i][idx_start] = 1


    
    elif day_type == 'early':


      for i in range(len(week_lst)):
        if b2b:
          r = rd.randint(1,2)
        else:
          r = rd.randint(2,3)
        idx_start = rd.randint(day_start, day_start+r)-r
        for j in range(week_lst[i]):
          idx_start +=r
          empty_calendar[i][idx_start] = 1


    elif day_type == 'late':
      

      for i in range(len(week_lst)):
        if b2b:
          r = rd.randint(1,2)
        else:
          r = rd.randint(2,3)
        idx_end = rd.randint(day_end-r, day_end)+r
        for j in range(week_lst[i]):
          idx_end -=r
          empty_calendar[i][idx_end] = 1

  
  elif week_type == 'early':
    week_lst = imb_week(5, False)
    #print(week_lst)

    if day_type == None:
      

      for i in range(len(week_lst)):
        if b2b:
          r = rd.randint(1,2)
        else:
          r = rd.randint(2,3)
        idx_start = rd.randint(day_start, day_end - week_lst[i]*r)-r
        
        for j in range(week_lst[i]):
          idx_start +=r
          empty_calendar[i][idx_start] = 1


    
    elif day_type == 'early':

      for i in range(len(week_lst)):
        if b2b:
          r = rd.randint(1,2)
        else:
          r = rd.randint(2,3)
        idx_start = rd.randint(day_start, day_start+r)-r
        for j in range(week_lst[i]):
          idx_start +=r
          empty_calendar[i][idx_start] = 1


    elif day_type == 'late':
      
      for i in range(len(week_lst)):
        if b2b:
          r = rd.randint(1,2)
        else:
          r = rd.randint(2,3)
        idx_end = rd.randint(day_end-r, day_end)+r
        for j in range(week_lst[i]):
          idx_end -=r
          empty_calendar[i][idx_end] = 1     
  
  elif week_type == 'late':
    
    week_lst = imb_week(5, True)
    #print(week_lst)
    
    if day_type == None:
      

      for i in range(len(week_lst)):
        if b2b:
          r = rd.randint(1,2)
        else:
          r = rd.randint(2,3)
        idx_start = rd.randint(day_start, day_end - week_lst[i]*r)-r
        
        for j in range(week_lst[i]):
          idx_start +=r
          empty_calendar[i][idx_start] = 1
     
    
    elif day_type == 'early':

      for i in range(len(week_lst)):
        if b2b:
          r = rd.randint(1,2)
        else:
          r = rd.randint(2,3)
        idx_start = rd.randint(day_start, day_start+r)-r
        for j in range(week_lst[i]):
          idx_start +=r
          empty_calendar[i][idx_start] = 1


    elif day_type == 'late':
      
      for i in range(len(week_lst)):
        if b2b:
          r = rd.randint(1,2)
        else:
          r = rd.randint(2,3)
        idx_end = rd.randint(day_end-r, day_end)+r
        for j in range(week_lst[i]):
          idx_end -=r
          empty_calendar[i][idx_end] = 1
  
  return empty_calendar




In [ ]:
def populate_calendar_3(max_per_day, week_type, day_type, b2b):

  empty_calendar = create_week(7, 24)
  
  day_start = 4
  day_end = 22
  week_len = 5
  #actual_per_day = rd.randint(max_per_week-2, max_per_day)
  
  early_week_idx = round(week_len//2)
  late_week_idx = round(week_len//2+1)
  max_per_week=week_len*max_per_day


  late_in_day = round(0.7*max_per_day)
  late_in_week = round(0.7*max_per_week)

  early_in_day = max_per_day - late_in_day
  early_in_week = max_per_week - late_in_week

  if week_type == None:

    week_lst =  [0,0,0,0,0,0,0]

    for i in range(len(week_lst)-week_len-1,week_len+1):
       week_lst[i] = rd.randint(max_per_day-2,max_per_day)
    #print('week_list:', week_lst)

    if day_type == None:

      for i in range(len(week_lst)):
        if b2b:
          idx_start = rd.randint(day_start, day_end - week_lst[i]*2)-2
        else:
          idx_start = rd.randint(day_start, day_end - week_lst[i]*3)-3
        
        for j in range(week_lst[i]):
          if b2b:
            r = rd.randint(1,2)
          else:
            r = rd.randint(2,3)
          idx_start +=r
          empty_calendar[i][idx_start] = 1


    
    elif day_type == 'early':


      for i in range(len(week_lst)):
        if b2b:
          idx_start = rd.randint(day_start, day_start+2)-2
        else:
          idx_start = rd.randint(day_start, day_start+3)-3

        for j in range(week_lst[i]):
          if b2b:
            r = rd.randint(1,2)
          else:
            r = rd.randint(2,3)
          idx_start +=r
          empty_calendar[i][idx_start] = 1


    elif day_type == 'late':
      

      for i in range(len(week_lst)):
        if b2b:
          idx_end = rd.randint(day_end-2, day_end)+2
        else:
          idx_end = rd.randint(day_end-2, day_end)+2
        for j in range(week_lst[i]):
          if b2b:
            r = rd.randint(1,2)
          else:
            r = rd.randint(2,3)
          idx_end -=r
          empty_calendar[i][idx_end] = 1
          
################################################################################
  elif week_type == 'early':
    week_lst = imb_week(5, False)
    #print(week_lst)
  
    if day_type == None:

      for i in range(len(week_lst)):
        if b2b:
          idx_start = rd.randint(day_start, day_end - week_lst[i]*2)-2
        else:
          idx_start = rd.randint(day_start, day_end - week_lst[i]*3)-3
        
        for j in range(week_lst[i]):
          if b2b:
            r = rd.randint(1,2)
          else:
            r = rd.randint(2,3)
          idx_start +=r
          empty_calendar[i][idx_start] = 1


    
    elif day_type == 'early':


      for i in range(len(week_lst)):
        if b2b:
          idx_start = rd.randint(day_start, day_start+2)-2
        else:
          idx_start = rd.randint(day_start, day_start+3)-3

        for j in range(week_lst[i]):
          if b2b:
            r = rd.randint(1,2)
          else:
            r = rd.randint(2,3)
          idx_start +=r
          empty_calendar[i][idx_start] = 1


    elif day_type == 'late':
      

      for i in range(len(week_lst)):
        if b2b:
          idx_end = rd.randint(day_end-2, day_end)+2
        else:
          idx_end = rd.randint(day_end-2, day_end)+2
        for j in range(week_lst[i]):
          if b2b:
            r = rd.randint(1,2)
          else:
            r = rd.randint(2,3)
          idx_end -=r
          empty_calendar[i][idx_end] = 1

################################################################################  
  elif week_type == 'late':
    
    week_lst = imb_week(5, True)
    # print(week_lst)
    
    if day_type == None:

      for i in range(len(week_lst)):
        if b2b:
          idx_start = rd.randint(day_start, day_end - week_lst[i]*2)-2
        else:
          idx_start = rd.randint(day_start, day_end - week_lst[i]*3)-3
        
        for j in range(week_lst[i]):
          if b2b:
            r = rd.randint(1,2)
          else:
            r = rd.randint(2,3)
          idx_start +=r
          empty_calendar[i][idx_start] = 1


    
    elif day_type == 'early':


      for i in range(len(week_lst)):
        if b2b:
          idx_start = rd.randint(day_start, day_start+2)-2
        else:
          idx_start = rd.randint(day_start, day_start+3)-3

        for j in range(week_lst[i]):
          if b2b:
            r = rd.randint(1,2)
          else:
            r = rd.randint(2,3)
          idx_start +=r
          empty_calendar[i][idx_start] = 1


    elif day_type == 'late':
      

      for i in range(len(week_lst)):
        if b2b:
          idx_end = rd.randint(day_end-2, day_end)+2
        else:
          idx_end = rd.randint(day_end-2, day_end)+2
        for j in range(week_lst[i]):
          if b2b:
            r = rd.randint(1,2)
          else:
            r = rd.randint(2,3)
          idx_end -=r
          empty_calendar[i][idx_end] = 1
  
  return empty_calendar


In [ ]:
for _ in range(50):
  populate_calendar_2(6,'early', None, False)

In [ ]:
week = ['early', 'late',None]
day = ['early', 'late',None]
b2b = [True, False]

In [ ]:
index = 0
for i in week:
  for j in day:
    for k in b2b:
      print(100*'-')
      print('Week:', i,'|', 'Day:', j,'|' 'b2b:', k)
      print(populate_calendar_3(5,i,j,k))
      print(100*'-')
      index+= 1
      print(index)
print('Total:', index)


----------------------------------------------------------------------------------------------------
Week: early | Day: early |b2b: True
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
----------------------------------------------------------------------------------------------------
1
----------------------------------------------------------------------------------------------------
Week: early | Day: early |b2b: False
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1

In [ ]:
#cal = populate_calendar(5,None, None, True)

In [ ]:
#new_frame = [[1,cal, None, None, True]]

In [ ]:
df = pd.DataFrame(columns=['Calendar', 'Week', 'Day', 'b2b', 'lbl_concat'])

In [ ]:
df

Empty DataFrame
Columns: [Calendar, Week, Day, b2b, lbl_concat]
Index: []

In [ ]:
week = ['early', 'late',None]
day = ['early', 'late',None]
b2b = [True, False]
ind = 0
for _ in range(500):
  index = 0
    
  for i in week:
    for j in day:
      for k in b2b:

        #print(i,j,k)
        cal = populate_calendar_3(5,i,j,k)
        ind+=1
        index+= 1
        df.loc[ind] = [cal] + [i,j,k] + [index]






In [ ]:
def label_row(row):
  tuple = [None,None,None]
  if row['Week'] == None:
    tuple[0] = 0
  if row['Week'] == 'early':
    tuple[0] = 1
  if row['Week'] == 'late':
    tuple[0] = 2
  if row['Day'] == None:
    tuple[1] = 0
  if row['Day'] == 'early':
    tuple[1] = 1
  if row['Day'] == 'late':
    tuple[1] = 2
  if row['b2b'] == True:
    tuple[2] = 0
  if row['b2b'] == False:
    tuple[2] = 1
  return tuple 



In [ ]:
df['label'] = df.apply(lambda row: label_row(row), axis=1)


In [ ]:
df.Calendar.duplicated().sum()

0

In [ ]:
df

Calendar  ...      label
1     [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  ...  [1, 1, 0]
2     [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  ...  [1, 1, 1]
3     [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  ...  [1, 2, 0]
4     [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  ...  [1, 2, 1]
5     [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  ...  [1, 0, 0]
...                                                 ...  ...        ...
8996  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  ...  [0, 1, 1]
8997  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  ...  [0, 2, 0]
8998  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  ...  [0, 2, 1]
8999  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  ...  [0, 0, 0]
9000  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  ...  [0, 0, 1]

[9000 rows x 6 columns]

In [ ]:
from google.colab import drive
drive.mount('drive')

Drive already mounted at drive; to attempt to forcibly remount, call drive.mount("drive", force_remount=True).


In [ ]:
df.to_csv('data_500_2.csv')
!cp data_500_2.csv "drive/My Drive/Preferences"

In [ ]:
type(df['Calendar'][1])

numpy.ndarray